version: "3.8"

services:
  ninjarig:
    build: .
    command: tail -f /dev/null
    image: eathtespagheti/ninjarig:cuda
    ports:
      - 8080:80
    volumes: 
      - ./config.json:/ninjarig/config.json